src/digitalmarket/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from checkout.views import CheckoutTestView, CheckoutAjaxView
from dashboard.views import DashboardView
from products.views import UserLibraryListView

urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^test/$', CheckoutTestView.as_view(), name='test'),
    url(r'^checkout/$', CheckoutAjaxView.as_view(), name='checkout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^seller/', include("sellers.urls", namespace='sellers')),
    url(r'^tags/', include("tags.urls", namespace='tags')),
    url(r'^library/', UserLibraryListView.as_view(), name='library'),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

src/tags/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
        TagDetailView,
        TagListView,
        )

urlpatterns = [
    url(r'^$', TagListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
]   

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	 <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
	<link rel='stylesheet' href='{% static "css/base.css" %}' />
<style>

.main-content {
	width: 800px;
	margin: 0 auto;
	clear:both;
}

.main-nav {
	width: 800px;
	margin: 10px auto;
}

.main-nav li {
	display: inline;
}

.first-nav {
	padding-left:0px;
}

.pull-right {
	float: right;
}

.pull-left {
	float: left;
}

.col-primary {
	width: 85%;
}

.col-sidebar {
	padding-top: 20px;
	width: 15%;
}

.clearfix {
	clear:both;
}

#purchage-btn {
	color: red;
}

button.buy-btn {
	border: 1px solid #DA5B00 !important;
	background: #DA5B00 !important;
}

button.buy-btn .ui-button-text {
	color: #ffffff;
}

.ui-widget-header {
	border: 1px solid #ffffff !important;
	background: #ffffff !important;
}

{% block style %}{% endblock style %}
</style>
</head>
<body>
<nav class='main-nav'>
	<ul class="pull-left first-nav">
		<li><a href='{% url "dashboard" %}'>Digital Marketplace</a></li>
	</ul>
	<ul class='pull-right'>
		<li><a href='{% url "products:list" %}'>Products</a></li>
		<li><a href='{% url "tags:list" %}'>Tags</a></li>
		<li><a href='{% url "library" %}'>Library</a></li>
	</ul>

</nav>
<div class='main-content'>
{% block content %}
<p>This is awesome</p>
{% endblock content %}

</div>
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>

<script src='{% static "js/django.csrf.js" %}'></script>

<script>
$(document).ready(function(){
	{% block jquery %}

	{% endblock jquery %}
})
</script>

</body>

</html>

src/templates/create_view.html
{% extends "base.html" %}


{% block content %}

{% include "form_include.html" with form=form submit_btn="Create Product" %}
{% endblock content %}

src/templates/detail_view.html
{% extends "base.html" %}


{% block content %}

<h1>Product: {{ object.title }}</h1>
<p>{{ object.description }}</p>
<p>{{ object.price }}</p>


{% endblock content %}

src/templates/form.html
{% extends "base.html" %}


{% block content %}

{% include "form_include.html" with form=form submit_btn=submit_btn %}


{% endblock content %}

src/templates/form_include.html
<form method="POST" action="" enctype='multipart/form-data'>
{% csrf_token %}
{{ form.as_p }}
<input type='submit' value='{% if submit_btn %}{{ submit_btn }}{% else %}Submit{% endif %}' />
</form>

src/templates/list_view.html
{% extends "base.html" %}

{% block style %}
h1 {
	color: green;
}
{% endblock style %}

{% block content %}


<h1>List View</h1>

{{ queryset }}

{% endblock content %}

src/templates/update_view.html
{% extends "base.html" %}


{% block content %}

{% include "form_include.html" with form=form submit_btn="Update Product" %}


{% endblock content %}